name: Node.js CI

on:
    pull_request:
        branches:
            - 'main'

jobs:
    setup:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14.x]

        steps:
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Cache node_modules
              id: node_modules_cache_id
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                  key: node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

            - name: Install dependencies
              run: yarn --frozen-lockfile

    lint:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14.x]

        steps:
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Restore cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                  key: node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

            - name: Run lint
              run: yarn lint

        needs: setup

    format:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14.x]

        steps:
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Restore cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                  key: node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

            - name: Run formater
              run: yarn format

        needs: setup

    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14.x]

        steps:
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Restore cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                  key: node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

            - name: Run test
              run: yarn test

        needs: setup
